version: "3.7"


services: 
    nginx:
        image: eisandbar/network:nginx
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        depends_on:
            - server
        ports:
            - "5100:5100"
        networks:
            web-net:
                aliases:
                    - api
        mem_limit: 16m
        mem_reservation: 16m
        cpus: 0.125
        restart: always
    
    server:
        image: eisandbar/network:server
        build: ./src/server
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.25"
                    memory: 64M
                reservations:
                    cpus: "0.125"
                    memory: 32M
        depends_on:
            - db
        volumes:
            - ./:/app
        networks:
            - db-net
            - web-net
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: pgdb
            POSTGRES_HOST: db
        restart: always
    
    client:
        image: eisandbar/network:client
        build: ./src/client
        depends_on:
            - server
        volumes:
            - ./:/app
        networks:
            - web-net
        mem_limit: 32m
        mem_reservation: 16m
        cpus: 0.125
        restart: always
    
    db:
        image: postgres
        volumes:
            - postgres:/var/lib/postgres
        networks:
            - db-net
        mem_limit: 64m
        mem_reservation: 32m
        cpus: 0.25
        restart: always
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: pgdb
    
    redis:
        image: eisandbar/network:redis
        build:
            context: ./redis/
            dockerfile: Dockerfile
        volumes:
            - redis:/data
        networks:
            - db-net
        mem_limit: 32m
        mem_reservation: 16m
        cpus: 0.125

networks:
    web-net:
        driver: overlay
        attachable: true
    db-net:
        driver: overlay
        attachable: true


volumes:
    postgres:
    redis: